name: 'Storybook Publish'

on:
  # TODO: Remove the push event before merging this PR
  push:
    branches:
      - storybook
  workflow_dispatch:
  pull_request:
    branches: "*"
    paths:
      - "*.stories.*"

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: 'npm'
      - run: npm install
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
